
export const TREECHARACTERISTICS = {
  age: [ 
    { optionLabel: "0-1 years", optionValue: '0-1'},
    { optionLabel: "2 years", optionValue: '2'},
    { optionLabel: "3 years", optionValue: '3'},
    { optionLabel: "4 years", optionValue: '4'},
    { optionLabel: "5 years", optionValue: '5'},
    { optionLabel: "6 years", optionValue: '6'},
    { optionLabel: "7 years", optionValue: '7'},
    { optionLabel: "8 years", optionValue: '8'},
    { optionLabel: "9 years", optionValue: '9'},
    { optionLabel: "10 years", optionValue: '10'},
    { optionLabel: "15-20 years", optionValue: '15-20'},
    { optionLabel: "20-30 years", optionValue: '20-30'},
    { optionLabel: "30-40 years", optionValue: '30-40'},
    { optionLabel: "40-50 years", optionValue: '40-50'},
    { optionLabel: "50-60 years", optionValue: '50-60'},
    { optionLabel: "60-69 years", optionValue: '60-69'},
    { optionLabel: "70-79 years", optionValue: '70-79'},
    { optionLabel: "80-89 years", optionValue: '80-89'},
    { optionLabel: "90-99 years", optionValue: '90-99'},
    { optionLabel: "100 years", optionValue: '100'},
    { optionLabel: "120 years", optionValue: '120'},
    { optionLabel: "130 years", optionValue: '130'},
    { optionLabel: "150 years", optionValue: '150'},
    { optionLabel: "200 years", optionValue: '200'},
    { optionLabel: "300 years", optionValue: '300'},
    { optionLabel: "400 years", optionValue: '400'},
  ],
  width: [
  { optionLabel: '<1 inch', optionValue: '<1 inch'},
  { optionLabel: '2 inch', optionValue: '2 inch'},
  { optionLabel: '3 inch', optionValue: '3 inch'},
  { optionLabel: '4 inch', optionValue: '4 inch'},
  { optionLabel: '5 inch', optionValue: '5 inch'},
  { optionLabel: '6 inch', optionValue: '6 inch'},
  { optionLabel: '8 inch', optionValue: '8 inch'},
  { optionLabel: '9 inch', optionValue: '9 inch'},
  ],
}

export const TREELOCATION = {
  state: [
    { optionValue: 'AK', optionLabel: 'Alaska'},
    { optionValue: 'AL', optionLabel: 'Alabama'},
    { optionValue: 'AR', optionLabel: 'Arkansas'},
    { optionValue: 'AZ', optionLabel: 'Arizona'},
    { optionValue: 'CA', optionLabel: 'California'},
    { optionValue: 'CO', optionLabel: 'Colorado'},
    { optionValue: 'CT', optionLabel: 'Connecticut'},
    { optionValue: 'DC', optionLabel: 'District of Columbia'},
    { optionValue: 'DE', optionLabel: 'Delaware'},
    { optionValue: 'FL', optionLabel: 'Florida'},
    { optionValue: 'GA', optionLabel: 'Georgia'},
    { optionValue: 'HI', optionLabel: 'Hawaii'},
    { optionValue: 'IA', optionLabel: 'Iowa'},
    { optionValue: 'ID', optionLabel: 'Idaho'},
    { optionValue: 'IL', optionLabel: 'Illinois'},
    { optionValue: 'IN', optionLabel: 'Indiana'},
    { optionValue: 'KS', optionLabel: 'Kansas'},
    { optionValue: 'KY', optionLabel: 'Kentucky'},
    { optionValue: 'LA', optionLabel: 'Louisiana'},
    { optionValue: 'MA', optionLabel: 'Massachusetts'},
    { optionValue: 'MD', optionLabel: 'Maryland'},
    { optionValue: 'ME', optionLabel: 'Maine'},
    { optionValue: 'MI', optionLabel: 'Michigan'},
    { optionValue: 'MN', optionLabel: 'Minnesota'},
    { optionValue: 'MO', optionLabel: 'Missouri'},
    { optionValue: 'MS', optionLabel: 'Mississippi'},
    { optionValue: 'MT', optionLabel: 'Montana'},
    { optionValue: 'NC', optionLabel: 'North Carolina'},
    { optionValue: 'ND', optionLabel: 'North Dakota'},
    { optionValue: 'NE', optionLabel: 'Nebraska'},
    { optionValue: 'NH', optionLabel: 'New Hampshire'},
    { optionValue: 'NJ', optionLabel: 'New Jersey'},
    { optionValue: 'NM', optionLabel: 'New Mexico'},
    { optionValue: 'NV', optionLabel: 'Nevada'},
    { optionValue: 'NY', optionLabel: 'New York'},
    { optionValue: 'OH', optionLabel: 'Ohio'},
    { optionValue: 'OK', optionLabel: 'Oklahoma'},
    { optionValue: 'OR', optionLabel: 'Oregon'},
    { optionValue: 'PA', optionLabel: 'Pennsylvania'},
    { optionValue: 'PR', optionLabel: 'Puerto Rico'},
    { optionValue: 'RI', optionLabel: 'Rhode Island'},
    { optionValue: 'SC', optionLabel: 'South Carolina'},
    { optionValue: 'SD', optionLabel: 'South Dakota'},
    { optionValue: 'TN', optionLabel: 'Tennessee'},
    { optionValue: 'TX', optionLabel: 'Texas'},
    { optionValue: 'UT', optionLabel: 'Utah'},
    { optionValue: 'VA', optionLabel: 'Virginia'},
    { optionValue: 'VT', optionLabel: 'Vermont'},
    { optionValue: 'WA', optionLabel: 'Washington'},
    { optionValue: 'WI', optionLabel: 'Wisconsin'},
    { optionValue: 'WV', optionLabel: 'West Virginia'},
    { optionValue: 'WY', optionLabel: 'Wyoming'},
  ]
};

export const TOP100TREES = [
  {
    CommonName: "Red Maple",
    BotanicalName: "Acer Rubrum",
    Cultivar: "Emperor",
    Notes: "",
  },
  {
    CommonName: "California Lilac",
    BotanicalName: "Ceanothus",
    Cultivar: "Juliana Phelps",
    Notes: "",
  },
  {
    CommonName: "Eastern Redbud",
    BotanicalName: "Eastern Redbud",
    Cultivar: "Weeping",
    Notes: "",
  },
  {
    CommonName: "Cherry",
    BotanicalName: "Cherry",
    Cultivar: "Weeping Snow Cherry",
    Notes: "",
  },
  {
    CommonName: "Santa Rosa Plum",
    BotanicalName: "Plum",
    Cultivar: "Weeping",
    Notes: "",
  },
  {
    CommonName: "Eureka Lemon",
    BotanicalName: "Citrus",
    Cultivar: "Eureka",
    Notes: "",
  },
];