name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: npm ci
        run: npm ci
      - name: Install chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get update
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.11.x
          npm run build
          lhci autorun \
            --only-categories=accessibility,best-practices \
            --collect.settings.chromeFlags="--no-sandbox --disable-gpu" \
            --disable-dev-shm-usage \
            --disable-storage-reset || echo "LHCI failed!"
